name: Update servers

on:
  schedule:
    - cron: "0 */4 * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Run filter
        run: python filter.py

      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add ru.txt
          git commit -m "Update ru.txt" || exit 0
          git pull --rebase origin main
          git push origin main
